name: Simple MATLAB Run

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2-beta
        with:
          release: 'latest'

      - name: Run MATLAB Script
        uses: matlab-actions/run-command@v1.2.0
        with:
          command: |
            % Your MATLAB code here
            disp("Hello, World!");